### ISSUE TITLE
Form validation relies on cleaned_data

### ISSUE THREAD

**Issue by nijel** [mosparo/django-integration#1]
Using `cleaned_data` for validation is wrong. It contains processed data, so it will fail for anything more complex (for example 
[ModelChoiceField](https://docs.djangoproject.com/en/4.1/ref/forms/fields/#modelchoicefield) will have a model instance there,
[JSONField](https://docs.djangoproject.com/en/4.1/ref/forms/fields/#jsonfield) will convert JSON string to a matching Python representation).

Problematic code:

https://github.com/mosparo/django-integration/blob/cc83ce279512af26144362857053caace29590e8/mosparo_django/fields.py#L65

Instead, it should look at `data` (and `files` if mosparo deals with those as well), what is the raw data as submitted in the form.

**Comment by zepich** [comment]
Hi @nijel 

Thank you very much for your feedback!

I've adjusted the field and changed the used property to `data` (see https://github.com/mosparo/django-integration/commit/373f0ffec17abb588280d20e24e90cab35d1fb80)

mosparo does not deal with `files` since there is no content to check for.
