### ISSUE TITLE
Field type CheckboxInput results in valid API submission, but return invalid result in Mosparo-Django

### ISSUE THREAD

**Issue by effizienzia** [mosparo/django-integration#2]
When trying to submit a Django form that contains a field of the type `CheckboxInput` the API returns a valid submission. However, the Mosparo-Django package returns that the submission was invalid. This seems to be because the list of `ignored_field_types` doesn't contain  `CheckboxInput`.  

**Steps to reproduce**
- Setup Django project to use Mosparo form validation
- Create form with Mosparo validation that contains a form field of type  `CheckboxInput` 
- Submit form in a way that should validate with respective Mosparo project rules and rulesets

**Expected Behaviour**
-  Mosparo shows valid form submission on the interface and Mosparo-Django returns valid form submission

**Current Behaviour**
- Mosparo shows valid form submission on the interface while Mosparo-Django returns *invalid* form submission

**Suggested Fix**
- Adding field types  `CheckboxInput`  to the list of `ignored_field_types`  solves the problem

**Version Number**
1.0.0

**Comment by zepich** [comment]
Hi @effizienzia 

Thank you very much for your very detailed issue. You're completely right; the two field types are not on the list of ignored field types.

I will adjust it later today and will release a new version.

Thank you very much for your help in making mosparo better!

Kind regards,

zepich

**Comment by zepich** [comment]
Hi @effizienzia 

As announced in my earlier post, I've just released a new version of the mosparo Django Integration, v1.0.2. This includes the BooleanField, the CheckboxInput, the RadioSelect, and other such classes, which mosparo will not process at all.

Please let me know if you need any help or have suggestions for the Django integration or mosparo.

I appreciate your help!

Kind regards,

zepich

**Comment by effizienzia** [comment]
works like a charm, thank you.
