### ISSUE TITLE
object has no attribute 'mosparo'

### ISSUE THREAD

**Issue by 21adrian1996** [mosparo/django-integration#3]
If I implement  the clean method with mosparo as described in the readme, Django returns

`{YOUR_FORM} object has no attribute 'mosparo'`

I think it is just a documentation issue and instead of

```
def clean(self):
    self.mosparo.verify_data(self)
    return super().clean()
```

it should be 

```
def clean(self):
    self.fields['mosparo'].verify_data(self)
    return super().clean()
```

**Comment by zepich** [comment]
Hi @21adrian1996 

Thank you very much for your report.

You're right! Thank you very much! I've fixed the mistake in the README.

Kind regards,

zepich
